### ISSUE TITLE
i2c_master_write does not detect write failures

### ISSUE THREAD

**Issue by jrmrjnck** [kontron/python-aardvark#10]
I've been using this library in a project quite successfully (thanks for making it easy to use!), but I've noticed that sometimes I2C writes don't go through and the API does not provide any indication of this. (There are multiple masters in my system, so probably it's losing arbitration.)

The root cause seems to be that Aardvark.i2c_master_write treats the return value of aa_i2c_write as a status code, when that function actually returns the number of bytes written. Therefore some exception should be raised whenever the return value is less than len(data). Or even better, use aa_i2c_write_ext which actually does return a status code (I'd really like to know if SLA_ACK, SLA_NACK, DATA_NACK, or ARB_LOST statuses occur).

**Comment by mwalle** [comment]
I guess the same is true for i2c_master_read. I'll change both to use the _ext functions.

**Comment by haggl** [comment]
I made the necessary changes in my fork. Are you interested in a pull request?

**Comment by mwalle** [comment]
yes please. sorry for having so less time :(

**Comment by haggl** [comment]
The patch is based on the pull-request I opened. Should I rebase it onto master so that you can merge it separately?

**Comment by mwalle** [comment]
yes please
