### ISSUE TITLE
Installation from tar.gz does not work on windows

### ISSUE THREAD

**Issue by oneilp6** [kontron/python-aardvark#11]
I have successfully imported pyaardvark however when i try to run the code below:

`import pyaardvark

a = pyaardvark.open()`

i get the errors below:

Traceback (most recent call last):
  File "C:\Users\oneilp6\Documents\python\1905_HOCD1_C1_602_B2\1905\Exercises\lab_eq\scratch.py", line 1, in <module>
    import pyaardvark
  File "build\bdist.win32\egg\pyaardvark__init__.py", line 22, in <module>
  File "build\bdist.win32\egg\pyaardvark\aardvark.py", line 52, in <module>
RuntimeError: Unable to find suitable binary interface. Unsupported platform?

Any ideas??

**Comment by hthiery** [comment]
can you try the following in a python script:

```
import sys
print sys.platform
```

if output starts with 'win' you could try to change aardvark.py line 32 to:

`elif sys.platform.startswith('win'):`

and run your script again.

**Comment by oneilp6** [comment]
The output is win32.  Should I still try the change?

**Comment by hthiery** [comment]
No, the change is not needed. The platform is ok. There seems to be a problem importing the api.

**Comment by hthiery** [comment]
how did you install the pyhton-aardvark? and what windows do you use?

**Comment by oneilp6** [comment]
I am on Windows 7.

I downloaded the tar.gz file and ran the setup using the following command

Python setup.py build
Python setup.py install


Thanks,
Pat

**Comment by hthiery** [comment]
can you try to import the binary interface manually from python interpreter:

```
from pyaardvark.ext.win32 import aardvark as api
dir(api)
```
and
```
from pyaardvark.ext.win64 import aardvark as api
dir(api)
```

**Comment by hthiery** [comment]
what python version do you use?

**Comment by oneilp6** [comment]
2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]


Thanks,
Pat

**Comment by oneilp6** [comment]
I get the same error when running both of the script examples


from pyaardvark.ext.win32 import aardvark as api

dir(api)

and

from pyaardvark.ext.win64 import aardvark as api

dir(api)
—

Thanks,
Pat

**Comment by hthiery** [comment]
It seems that the lib is not Installer correct. Please try to install with
pip.
Am 29.04.2016 16:05 schrieb "oneilp6" <notifications@github.com>:

**Comment by oneilp6** [comment]
Yeah my PIP install is not working properly either that’s why I installed it the other way

I always get this error when installing with PIP and I cant figure out why
C:\Python27>pip install pyaardvark
C:\strawberry\perl\bin/pip: Perl lib version (5.22.0) doesn't match executable '
C:\strawberry\perl\bin\perl.exe' version (5.16.3) at C:/strawberry/perl/lib/Conf
ig.pm line 62.
Compilation failed in require at C:/strawberry/perl/lib/Errno.pm line 8.
BEGIN failed--compilation aborted at C:/strawberry/perl/lib/Errno.pm line 8.
Compilation failed in require at C:/strawberry/perl/lib/File/Temp.pm line 148.
BEGIN failed--compilation aborted at C:/strawberry/perl/lib/File/Temp.pm line 14
8.
Compilation failed in require at C:/strawberry/perl/vendor/lib/pip.pm line 6.
BEGIN failed--compilation aborted at C:/strawberry/perl/vendor/lib/pip.pm line 6
.
Compilation failed in require at C:\strawberry\perl\bin/pip line 5.
BEGIN failed--compilation aborted at C:\strawberry\perl\bin/pip line 5.

Thanks,
Pat

**Comment by oneilp6** [comment]
I got the PIP fixed, the install worked from PIP

Thanks,
Pat

**Comment by oneilp6** [comment]
One more question, I am trying to read from  address 0x59 that has 13 bytes with the write command being 99h.  What is the best way to write the hex value through the master_read_write?

For instance I write 99h to an aardvark and the read I get is a serial number.

Thanks,
Pat

**Comment by hthiery** [comment]
Did you take a look at http://pyaardvark.readthedocs.io/en/latest/intro.html?

**Comment by oneilp6** [comment]
Thanks for all the helpw, after reading the docs, I got pyaardvark to work with a single read.  However when I try to loop through addresses it keeps reading the first write that it performs.  The first address is a date, but then it just keeps returning the date.  If I run each address individually they work fine, just not in a loop

`
import pyaardvark
import time

addresses = ['98', '99','9A','9B', '9C', '9D', '9E']
p_fix = '\\x'

a = pyaardvark.open()
for item in addresses:

    address = p_fix + item
    print address
    data = a.i2c_master_write_read(0x59, address , 13)
    print data
    time.sleep(3)

a.close()
`

**Comment by hthiery** [comment]
For more information about handling data to write and handle data read back check the newly added FAQ section in the documentation.
