### ISSUE TITLE
What work would be required to support python 3

### ISSUE THREAD

**Issue by andrewkenny** [kontron/python-aardvark#13]
Hi,
I really like this project, and I am sure I could contribute.

I have done work (outside of github) on converting python projects to be python 2/3 agnostic.
But I havn't done any DLL communication or anything like that.

So what I am saying is, if I submit a pull request containing updates to python3, would somebody be willing to ensure that the python3 executable works with the aardvark dll?

**Comment by mwalle** [comment]
Am 2016-07-04 13:26, schrieb andrewkenny:
> Hi,
> I really like this project, and I am sure I could contribute.
> 
> I have done work (outside of github) on converting python projects to
> be python 2/3 agnostic.
> But I havn't done any DLL communication or anything like that.
> 
> So what I am saying is, if I submit a pull request containing updates
> to python3, would somebody be willing to ensure that the python3
> executable works with the aardvark dll?

Hi Andrew,

AFAIK the (binary) shared object must match the python version. So 
unless Totalphase releases a python 3 module, we are stuck with python 
2.

-michael

**Comment by andrewkenny** [comment]
What about modifying the C bindings to act as a python3 module?
 (I am speaking like I know what I am talking about - I am only speculating)

**Comment by hthiery** [comment]
as fas as i know the c binaries come from totalphase and you have to talk
to them about modifying this code...

2016-07-04 14:32 GMT+02:00 andrewkenny <notifications@github.com>:

**Comment by andrewkenny** [comment]
I think I explained what I meant poorly.

The API includes example .C files which call the functions within the provided dll.

therefore, couldnt a new dll be made which calls functions from the current one?

This new dll would of course have python3 bindings attached to it.

**Comment by mwalle** [comment]
Am 2016-07-04 15:01, schrieb andrewkenny:
> I think I explained what I meant poorly.
> 
> The API includes example .C files which call the functions within the
> provided dll.
> 
> therefore, couldnt a new dll be made which calls functions from the
> current one?
> 
> This new dll would of course have python3 bindings attached to it.

OK i guess that could work with the c binding (ie not the python 2 .so 
file).

**Comment by abhilashreddyp** [comment]
Hi, Did you find the solution for this. Whether you modifying the C bindings to act as a python3 module?

**Comment by mwalle** [comment]
Totalphase had a new api version v5.30, which I believe, supports python 3. I've updated the modules, but didn't look into the python3 support for our python code. But this definitely looks better now.

I know this is a very old thead, but just to let you know there might be some development here ;)

**Comment by mwalle** [comment]
python-aardvark version 0.6.1 has python 3 support
