### ISSUE TITLE
PyInstaller and Total Phase dll

### ISSUE THREAD

**Issue by nosjojo** [kontron/python-aardvark#27]
I was fighting with this one recently and finally sorted it out with some help from the PyInstaller devs and some info from Total Phase. I wanted to mention it here so it could be documented for future users, especially if someone updates to newer pyaardvark versions.

The newest versions of the aardvark.dll, from version 5.60+, now have a python3.dll requirement baked into them. This seems to manifest into a few odd issues, particularly the popup messages of "OSError: [Errno -2] unable to load usb driver" and "Unable to bind API".

This error comes from one of two different sources, from what I've seen.
- The python version is incompatible with the aardvark.dll version
- There is an issue with detection of python3.dll

For PyInstaller specifically, the python3.dll isn't being included automatically in the build, so I get the errors above depending on which version of pyaardvark I'm running. The instructions to correct for this can be found here: https://github.com/pyinstaller/pyinstaller/discussions/7326#discussioncomment-4403492

If you know you have the correct python version and are seeing one of these errors, it may be related to the python3.dll not being detected, especially if you are running a separate program that is interfacing with python to run your code, rather than directly in the interpreter.

**Comment by mwalle** [comment]
Would it make sense to integrate pyinstaller support into pyaardvark? Maybe we can build the packages automatically with github actions (?).

-michael

**Comment by mwalle** [comment]
Closed due to inactivity.
