### ISSUE TITLE
Device is always in use

### ISSUE THREAD

**Issue by tnorth** [kontron/python-aardvark#31]
Hi there,

I noticed that opening the device fails with an IO Error (device in use) whenever using pyaardvark from a remote session (SSH or Remote desktop).

Does the library depend on some environment variable not defined in remote sessions? Any hint/workaround?

**Comment by mwalle** [comment]
Can you elaborate a bit more please? Do you use SSH to open a remote shell and then use pyaardvark?

**Comment by tnorth** [comment]
Yes, exactly. I connect to the machine via SSH and use pyaardvark from there (in ipython for testing for instance).
I noticed the same problem when accessing the machine remotely via RDP.

**Comment by tnorth** [comment]
A few more details, this is with a Linux machine (Fedora 37), x86_64.
Using pyaardvark when logged in locally on the machine directly works without issue.
I haven't checked the code in detail, but it looks like the whole device discovery/opening is done within the (proprietary) shared object (py_aa_open_ext() etc.) :-/

**Comment by mwalle** [comment]
I'm not really sure how to help here as the lib is just working fine locally. If you have any further details or how to fix your problem, please feel free to reopen the issue.
