### ISSUE TITLE
Aardvark Software API v6.00

### ISSUE THREAD

**Issue by cranechu** [kontron/python-aardvark#32]
Hi, 

Total Phase officially released the new API (v6.00). Could you please also make an update? Thanks very much!
Here is the link: https://www.totalphase.com/products/aardvark-software-api/#
We verified this new API version, and it did solved the issue we observed on the latest Ubuntu 22.04. 

Thanks!

**Comment by mwalle** [comment]
Unfortunately, totalphase removed the monitoring support in 6.00. No mention of this in the CHANGES.txt though.

**Comment by cranechu** [comment]
Yes. The CHANGES log is not fully maintained. :) Even though, are you willing to upgrade API to v6.00 in pyaardvark? Thanks!

**Comment by mwalle** [comment]
Eventially, yes. But it is a major change if the monitoring support is ineed removed. I've asked Totalphase.

In any case, could you give the feature branch a try? Thanks.

**Comment by cranechu** [comment]
Sure, I can try the branch. But pypi is better. :)

**Comment by mwalle** [comment]
Ok, I'll wait for your feedback on the 6.00 branch. Thanks.

**Comment by cranechu** [comment]
Hi, I have tested the branch feature-api-6.00. It works well with my NVMe MI test scripts. https://nvmexpress.org/specification/nvme-mi-specification/

Could you please update it to PyPI? Thanks!

**Comment by webmeister** [comment]
Tested on Raspberry Pi 5 (aarch64), seems to work fine. Looking forward to the update on PyPI :)

**Comment by mwalle** [comment]
Thanks! Just pushed onto the master branch. New release will follow soon.
