### ISSUE TITLE
MacOS 10.10/Python2.7 not working

### ISSUE THREAD

**Issue by frankhonore** [kontron/python-aardvark#8]
I installed with 'easy_install pyaardvark' on Yosemite and get the following error:

    import pyaardvark
  File "build/bdist.macosx-10.10-intel/egg/pyaardvark/__init__.py", line 22, in <module>

  File "build/bdist.macosx-10.10-intel/egg/pyaardvark/aardvark.py", line 52, in <module>
RuntimeError: Unable to find suitable binary interface. Unsupported platform?

Is it not supported on Yosemite? Or am I missing something I need.

Thanks,
Frank

**Comment by mwalle** [comment]
Hi Frank,

please try the following:

    python -c 'import sys; print sys.platform'

does it print 'darwin' ? If this is true, try to import the modules manually (cd to your local git clone, make sure it is installed or the PYTHONPATH is set correctly):

    python -c 'from pyaardvark.ext.osx32 import aardvark'
    python -c 'from pyaardvark.ext.osx64 import aardvark'

Please paste the output here.

**Comment by frankhonore** [comment]
$ python -c 'import sys; print sys.platform'
darwin
$ python -c 'from pyaardvark.ext.osx32 import aardvark'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.macosx-10.10-intel/egg/pyaardvark/__init__.py", line
22, in <module>
  File "build/bdist.macosx-10.10-intel/egg/pyaardvark/aardvark.py", line
52, in <module>
RuntimeError: Unable to find suitable binary interface. Unsupported
platform?
$ python -c 'from pyaardvark.ext.osx64 import aardvark'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.macosx-10.10-intel/egg/pyaardvark/__init__.py", line
22, in <module>
  File "build/bdist.macosx-10.10-intel/egg/pyaardvark/aardvark.py", line
52, in <module>
RuntimeError: Unable to find suitable binary interface. Unsupported
platform?

Thanks for the help!
Frank

**Comment by mwalle** [comment]
Am 2015-10-08 17:03, schrieb frankhonore:
> $ python -c 'import sys; print sys.platform'
>  darwin

ok.

>  $ python -c 'from pyaardvark.ext.osx32 import aardvark'
>  Traceback (most recent call last):
>  File "<string>", line 1, in <module>
>  File "build/bdist.macosx-10.10-intel/egg/pyaardvark/__init__.py",
> line
>  22, in <module>
>  File "build/bdist.macosx-10.10-intel/egg/pyaardvark/aardvark.py",
> line
>  52, in <module>
>  RuntimeError: Unable to find suitable binary interface. Unsupported
>  platform?
>  $ python -c 'from pyaardvark.ext.osx64 import aardvark'
>  Traceback (most recent call last):
>  File "<string>", line 1, in <module>
>  File "build/bdist.macosx-10.10-intel/egg/pyaardvark/__init__.py",
> line
>  22, in <module>
>  File "build/bdist.macosx-10.10-intel/egg/pyaardvark/aardvark.py",
> line
>  52, in <module>
>  RuntimeError: Unable to find suitable binary interface. Unsupported
>  platform?
> 

mh that didn't work. could you try to clone the github repository and do 
the same command with the PYTHONPATH=/path/to/python-aardvark 
environment variable?

there should be another error than "Unabe to find suitable binary 
interface".

-michael

**Comment by frankhonore** [comment]
Unfortunately, same runtime error and no new information.

Anyone having luck on Yosemite?

**Comment by vitb** [comment]
Guys,

would you please check - githib bugs me that there is no payment received.
It seems that the card which maintains the access is expired or something.

Chris: hope all is fine on your side!

-V

On Wed, Oct 14, 2015 at 3:15 AM, frankhonore <notifications@github.com>
wrote:

> Unfortunately, same runtime error and no new information.
>
> Anyone having luck on Yosemite?
>
> On Fri, Oct 9, 2015 at 2:50 AM, Michael Walle <notifications@github.com>
> wrote:
>
> > Am 2015-10-08 17:03, schrieb frankhonore:
> > > $ python -c 'import sys; print sys.platform'
> > > darwin
> >
> > ok.
> >
> > > $ python -c 'from pyaardvark.ext.osx32 import aardvark'
> > > Traceback (most recent call last):
> > > File "<string>", line 1, in <module>
> > > File "build/bdist.macosx-10.10-intel/egg/pyaardvark/__init__.py",
> > > line
> > > 22, in <module>
> > > File "build/bdist.macosx-10.10-intel/egg/pyaardvark/aardvark.py",
> > > line
> > > 52, in <module>
> > > RuntimeError: Unable to find suitable binary interface. Unsupported
> > > platform?
> > > $ python -c 'from pyaardvark.ext.osx64 import aardvark'
> > > Traceback (most recent call last):
> > > File "<string>", line 1, in <module>
> > > File "build/bdist.macosx-10.10-intel/egg/pyaardvark/__init__.py",
> > > line
> > > 22, in <module>
> > > File "build/bdist.macosx-10.10-intel/egg/pyaardvark/aardvark.py",
> > > line
> > > 52, in <module>
> > > RuntimeError: Unable to find suitable binary interface. Unsupported
> > > platform?
> > >
> >
> > mh that didn't work. could you try to clone the github repository and do
> > the same command with the PYTHONPATH=/path/to/python-aardvark
> > environment variable?
> >
> > there should be another error than "Unabe to find suitable binary
> > interface".
> >
> > -michael
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/kontron/python-aardvark/issues/8#issuecomment-146816818
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kontron/python-aardvark/issues/8#issuecomment-147897768>
> .
>



-- 
Sincerely, Vitaly

**Comment by mwalle** [comment]
maybe @abardagjy know something more, he had committed the MacOS support.

**Comment by abardagjy** [comment]
```$ python -c 'from pyaardvark.ext.osx32 import aardvark```

try pyaardvark,ex.osx64?

**Comment by abardagjy** [comment]
Is this a permissions issue? If you sudo easy_installed it, you might not be able to see the binary when you try to import it

**Comment by mwalle** [comment]
it puzzles me that he still gets my error message even when he tries to import the shared object directly. actually, i expect the underlying import error message. 

Am 17. Oktober 2015 03:13:25 MESZ, schrieb Andy Bardagjy <notifications@github.com>:
>Is this a permissions issue? If you sudo easy_installed it, you might
>not be able to see the binary when you try to import it
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kontron/python-aardvark/issues/8#issuecomment-148873740

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by frankhonore** [comment]
Update: installing with pip seems to work. Not sure why I had trouble with
easy_install.

Thanks for the help!
Frank

**Comment by abardagjy** [comment]
Hrm, I'll bet it was a permissions issue.. glad to hear that it's working for you!
